### ISSUE TITLE
current version does not build

### ISSUE THREAD

**Issue by Kynneb** [ESROCOS/gui-vizkit3d_taste#2]
As described, the error message is:

```
CMake Error at /root/esrocos_workspace/install/cmake_macros/esrocos.cmake:451 (list):
[J      list sub-command REMOVE_ITEM requires two or more arguments.
[J    Call Stack (most recent call first):
[J      models/trajectory/CMakeLists.txt:5 (esrocos_build_taste)
```

**Comment by mmunoz-gmv** [comment]
Traced to an issue at first build after downloading from GitHub. It should be solved now. However, the package doesn't build yet due to a possible bug in mono. Building just the gui/vizkit3d_taste package with amake does seem to work. It fails when doing autoproj build for the entire thing. As a workaround, if the package fails, build it individually, and then continue the build of the entire ESROCOS.
